### ISSUE TITLE
Beaglebone target missing from kubos.mk

### ISSUE THREAD

**Issue by Psykar** [kubostech/kubos-linux-build#49]
https://github.com/kubostech/kubos-linux-build/blob/master/package/kubos/kubos.mk#L21

Additionally the else branch not having KUBOS_TARGET set seems to break on my buildchain - I'm not super familiar with buildroot, but it seems that this method of raising an error isn't particuarly robust (ie. I wasn't actually getting the 'unknown target' error that this line suggests should occur.

**Comment by CatGarab** [comment]
There are definitely a few improvements that need to be made. The kubos.mk file was created and tested against the ISIS-OBC, which is our current officially supported target; the error case wasn't properly tested (that's on me). The beaglebone black target is not officially supported yet and does have some outstanding work remaining. This will be fixed some time in the next week or two.

If you'd like to get the beaglebone target to work for now, there are a few things you'll need to do:
- Replace the kubos.mk file's `else` case line with `KUBOS_TARGET = kubos-linux-beaglebone-gcc`
- Run this command: `sudo apt-get install crossbuild-essential-armhf gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf`
- Re-run `make` from your buildroot folder. If you get any weird errors, try running `make kubos-deepclean` and then re-running `make`

If you're planning on creating a Kubos SDK project to go on your beaglebone, you'll need to run two more commands:
- `kubos use 1.0.0.1` (the latest build of the SDK, which includes the new beaglebone target)
- `kubos link -a`

**Comment by Psykar** [comment]
Already got one working actually, using much the same as what you've just mentioned. Thanks though, figured I'd still open the issue :)

**Comment by CatGarab** [comment]
Awesome! We absolutely appreciate the feedback!

**Comment by Psykar** [comment]
Looks like this was fixed in e5ad3ca527c6e71d10ed76bd78672dee3f6061f8
